### ISSUE TITLE
Goddess Statue item desc bug

### ISSUE THREAD

**Issue by Sultia** [Tictim/Paraglider#104] opened 2023-11-29 16:05 UTC
![image](https://github.com/Tictim/Paraglider/assets/22875591/b16faff2-a2d5-43b7-86cb-bff706e99b2c)
![image](https://github.com/Tictim/Paraglider/assets/22875591/f53d1426-f73a-4f4f-8e9f-4cef5d9fb9b5)

Every goddess statue has this visual issue.

Mod ver: 20.1.1

MC ver: 1.20.1

**Comment by Tictim** [comment] 2023-12-03 05:29
Duplicate of #90.

**Closed as completed by Tictim** 2023-12-03 05:29 UTC
