### ISSUE TITLE
Paragliding animation doesn't work in 1.12

### ISSUE THREAD

**Issue by PessiPanto** [Tictim/Paraglider#8] opened 2020-12-08 10:27 UTC
hey so I just tried out the 1.12 mod and it appears to not work just right... when im using the paraglider if i look in third person i still am just holding the item in my hand like normal instead of the special paraglider animation. i dont have any other mods that are coremods?

**Comment by Tictim** [comment] 2020-12-08 11:49
First of all, you might notice the issue looks somewhat hideous because you shoved entire stanza of description in the title. The easiest solution would be, well, putting description in description, with title that summarizes the problem well. I'll do it for ya.

Second, there's still not enough information. "No mods that are coremods" isn't... very helpful information, or trustworthy one.

The best you could do in this situation is **providing entire game logs.** It's the file named `debug.log` and it's located in `logs` folder, inside game folder itself. Put it in paste site like [Gist](https://gist.github.com/) and send the link to this thread. Then I could atleast look and tell something about it.

And lastly, sorry to say it, but **we don't provide support or update targeting other than 1.15/1.16.** It means even if the issue is confirmed real and there's no way to make it work except fix the code, I won't fix that. You probably have to play more modern version of Minecraft or give up and live with the bugs, if that's the case.

Closing issue because the issue is from legacy version. You may still contact me, but bear in mind I won't do any work for legacy version.

**Closed as completed by Tictim** 2020-12-08 11:49 UTC
Labels: wontfix
