### ISSUE TITLE
Too many upwind firework particles causing timeouts on servers

### ISSUE THREAD

**Issue by Marteinstr** [Tictim/Paraglider#63] opened 2022-10-18 14:16 UTC
Added lava to upwind sources on a server, issue is that on big lava lakes the overload of firework particles reaches the server's threshold and causes the server to timeout everybody while it clears the particles or something like that. 

Could it be possible to implement an option in the paraglider-server.toml to limit(or set to a chosen value?), or even disables the firework particles produced by the paraglider mod?

Thanks a lot.

![unknown](https://user-images.githubusercontent.com/116091578/196455939-b87094e6-a678-4f58-9ed1-15da31a9463d.png)

**Comment by Marteinstr** [comment] 2022-10-18 14:18
mod version is "Paraglider-1.19.2-1.7.0.1"

**Comment by Tictim** [comment] 2022-11-09 11:10
Sorry for ignoring the issue for so long.

Particle placement is handled entirely on client side. The issue is likely caused by erroneous serialization/deserialization of wind chunk. Fix for suspected part of code will be included in the next release.

**Closed as completed** 2022-11-15 06:32 UTC
