### ISSUE TITLE
Changing Spirit orb drops from a mob spawner

### ISSUE THREAD

**Issue by Kuggle01** [Tictim/Paraglider#68] opened 2022-12-18 15:46 UTC
I wanna know if it's possible to change the number of spirit orbs dropped from a mob spawner. spefically I would like to change it from 4 to 1

**Comment by Tictim** [comment] 2022-12-20 03:23
Duplicate of #55.

Yes, it's possible. Spirit orb drop is controlled by loot datapack, specifically loot modifier system added by Forge. As it is datapack entry, you can freely modify those.

One thing worth mentioning is that the default orb drop from spawner is 2 each, not 4. It is suspected that another mod somehow makes the loot drop triggered twice for some god forbid reason, but I do not have further information.

I will close the issue, but feel free to ask further questions. If you have found out something about double drop issue, please let me know.

**Closed as completed by Tictim** 2022-12-20 03:23 UTC
