### ISSUE TITLE
Crash on startup after updating from 1.2.0.0 to 1.2.1.0

### ISSUE THREAD

**Issue by Sweed-Le-Deedly** [Tictim/Paraglider#1] opened 2020-08-21 14:06 UTC
Seems that the new update had a few issues for me; can't even get to the main menu of Minecraft itself before it crashes back to launcher saying that the Registery Object for paraglider is not present. I wonder if I have another coremod that conflits with Paraglider itself.

> ---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 8/21/20 10:00 AM
> Description: Initializing game
> 
> java.lang.NullPointerException: Registry Object not present: paraglider:paraglider
> 
> 	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:classloading}
> 	at tictim.paraglider.ParagliderMod$ClientHandler.addColorHandler(ParagliderMod.java:77) ~[?:1.2.1.0] {re:classloading,pl:eventbus:A}
> 	at net.minecraftforge.eventbus.ASMEventHandler_164_ClientHandler_addColorHandler_Item.invoke(.dynamic) ~[?:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader$$Lambda$4794/2037929227.accept(Unknown Source) ~[?:?] {}
> 	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
> 	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212) ~[?:?] {re:classloading}
> 	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:modernui:(Method2ClassTransformerWrapper) replaceDisplayIngameMenu,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.30.jar:31.2] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$449/1714153975.call(Unknown Source) [forge-1.15.2-31.2.30.jar:31.2] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at java.util.Objects.requireNonNull(Objects.java:290)
> 	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120)
> 	at tictim.paraglider.ParagliderMod$ClientHandler.addColorHandler(ParagliderMod.java:77)
> 	at net.minecraftforge.eventbus.ASMEventHandler_164_ClientHandler_addColorHandler_Item.invoke(.dynamic)
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
> 	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
> 	at net.minecraftforge.fml.ModLoader$$Lambda$4794/2037929227.accept(Unknown Source)
> 	at java.util.HashMap.forEach(HashMap.java:1280)
> 	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
> 	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
> 	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212)
> 	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84)
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(SourceFile:166)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$449/1714153975.call(Unknown Source)
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.15.2
> 	Minecraft Version ID: 1.15.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1335718440 bytes (1273 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 8
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	ModLauncher: 5.1.0+69+master.79f13f7
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
> 		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
> 		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
> 		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
> 	FML: 31.2
> 	Forge: net.minecraftforge:31.2.30
> 	FML Language Providers: 
> 		javafml@31.2
> 		minecraft@1
> 		kotlinfml@1.5.2
> 	Mod List: 
> 		enchantedbookredesign-2.0a.jar Enchanted Book Redesign {enchantedbookredesign@2.0a CREATE_REGISTRIES}
> 		doubledoors_1.15-2.1.jar Double Doors {doubledoors@2.1 CREATE_REGISTRIES}
> 		foodexpansion-1.5.2.jar Food Expansion: Reimagined {foodexpansion@1.5.2 CREATE_REGISTRIES}
> 		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 CREATE_REGISTRIES}
> 		JACM-1.1-1.15.2.jar Just Another Compass Mod {elenaicompass@1.0 CREATE_REGISTRIES}
> 		zombiehs_1.15-2.4.jar Zombie Horse Spawn {zombiehs@2.4 CREATE_REGISTRIES}
> 		ElenaiDodge-1.15.2-1.7.2.jar Elenai Dodge {elenaidodge@1.15.2-1.7.2 CREATE_REGISTRIES}
> 		HappyTrails-1.15.2-1.0.0.2.jar Happy Trails Mod {ht@1.0.0.2 CREATE_REGISTRIES}
> 		beenfo-1.0.3-bb.jar Beenfo {beenfo@1.0.3-bb CREATE_REGISTRIES}
> 		treeharvester_1.15-1.3.jar Tree Harvester {treeharvester@1.3 CREATE_REGISTRIES}
> 		Mine+and+Slash-1.15.2-3.6.14.jar Mine and Slash {mmorpg@3.6.14 CREATE_REGISTRIES}
> 		curiousshulkerboxes-FORGE-1.15.2-2.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.15.2-2.0.1 CREATE_REGISTRIES}
> 		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 CREATE_REGISTRIES}
> 		longfallboots-1.4.0c.jar Long Fall Boots {longfallboots@1.4.0c CREATE_REGISTRIES}
> 		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 CREATE_REGISTRIES}
> 		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 CREATE_REGISTRIES}
> 		despeggshatch_1.15-1.3.jar Despawning Eggs Hatch {despeggshatch@1.3 CREATE_REGISTRIES}
> 		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 CREATE_REGISTRIES}
> 		skeletonhs_1.15-1.3.jar Skeleton Horse Spawn {skeletonhs@1.3 CREATE_REGISTRIES}
> 		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d CREATE_REGISTRIES}
> 		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
> 		vmt-1.15.2-1.3.jar Villager Memory Tweaks {vmt@1.15.2-1.0 CREATE_REGISTRIES}
> 		RingOfRepair-1.15.2-1.1.33.jar Ring of Repair {ring_of_repair@1.1.30 CREATE_REGISTRIES}
> 		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 CREATE_REGISTRIES}
> 		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 CREATE_REGISTRIES}
> 		TravelersBackpack-1.15.2-4.0.5.jar Traveler's Backpack {travelersbackpack@4.0.5 CREATE_REGISTRIES}
> 		SereneSeasons-1.15.2-3.0.0.73-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.73 CREATE_REGISTRIES}
> 		sneakthroughberries-1.15.2-20w06a-1.0.1.jar Sneak Through Berries {sneakthroughberries@1.15.2-20w06a-1.0.1 CREATE_REGISTRIES}
> 		humblingbundle_1.15-1.3.jar Humbling Bundle {humblingbundle@1.3 CREATE_REGISTRIES}
> 		potionsmaster-0.1.7-1.15.2-31.2.0.jar Potions Master {potionsmaster@0.1.7 CREATE_REGISTRIES}
> 		FarmingForBlockheads_1.15.2-6.1.4.jar Farming for Blockheads {farmingforblockheads@6.1.4 CREATE_REGISTRIES}
> 		branders-enhanced-spawnermod-1.15.2-1.6.5.jar Enhanced Mob Spawners {spawnermod@1.6.5 CREATE_REGISTRIES}
> 		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
> 		BedBenefits-1.15.2-1.0.4.jar BedBenefits {bedbenefits@1.0.4 CREATE_REGISTRIES}
> 		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 CREATE_REGISTRIES}
> 		u_team_core-1.15.2-3.0.0.160.jar U Team Core {uteamcore@3.0.0.160 CREATE_REGISTRIES}
> 		bamboospreads_1.15-1.1.jar Bamboo Spreads {bamboospreads@1.1 CREATE_REGISTRIES}
> 		cryingghasts_1.15-1.1.jar Crying Ghasts {cryingghasts@1.1 CREATE_REGISTRIES}
> 		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 CREATE_REGISTRIES}
> 		spidersprwebs_1.15-1.1.jar Spiders Produce Webs {spidersprwebs@1.1 CREATE_REGISTRIES}
> 		enchantability-8.1.jar Enchantability {enchantability@8.1 CREATE_REGISTRIES}
> 		carpetstairsmod-1.15.2_v1.4.7.jar Carpet Stairs Mod {carpetstairsmod@1.4.7 CREATE_REGISTRIES}
> 		ForSale+simple+mod+1.15.2+1.2.jar ForSale {forsale@1.0.0 CREATE_REGISTRIES}
> 		Paraglider-1.15.2-1.2.1.0.jar Paraglider {paraglider@1.2.1.0 CREATE_REGISTRIES}
> 		forge-1.15.2-31.2.30-universal.jar Forge {forge@31.2.30 CREATE_REGISTRIES}
> 		BetterSwim+1.15+1.0.0.jar BetterSwim {betterswim@1.0.0 CREATE_REGISTRIES}
> 		scuba-gear-1.15.2-1.0.0.jar Scuba Gear {scuba_gear@1.0.0 CREATE_REGISTRIES}
> 		world_generation_profiler-1.15.2-1.4.0.8.jar World Generation Profiler {worldgenerationprofiler@1.4.0.8 CREATE_REGISTRIES}
> 		corpse-1.15.2-1.0.6.jar Corpse {corpse@1.15.2-1.0.6 CREATE_REGISTRIES}
> 		villagerdeathm_1.15.2-1.5.jar Villager Death Messages {villagerdeathm@1.5 CREATE_REGISTRIES}
> 		anviltweaks-2.3.jar Anvil Tweaks {anviltweaks@2.3 CREATE_REGISTRIES}
> 		forge-1.15.2-31.2.30-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
> 		dwmh-1.15.2-4.0.0.jar Dude! Where's my Horse? {dwmh@NONE CREATE_REGISTRIES}
> 		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 CREATE_REGISTRIES}
> 		morezombiev_1.15-1.1.jar More Zombie Villagers {morezombiev@1.1 CREATE_REGISTRIES}
> 		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 CREATE_REGISTRIES}
> 		bspawncontrol_1.15-1.1.jar Better Spawner Control {bspawncontrol@1.1 CREATE_REGISTRIES}
> 		flora-doubling-1.15.2-1.1.1.jar Flora Doubling {flora-doubling@1.15.2-1.1.1 CREATE_REGISTRIES}
> 		inventorytotem_1.15-1.1.jar Inventory Totem {inventorytotem@1.1 CREATE_REGISTRIES}
> 		adventurepack-1.0.jar Adventure Tools {adventurepack@1.15.2-1.0 CREATE_REGISTRIES}
> 		towers_of_the_wild-1.15.2-1.2.0.jar Towers Of the Wild {towers_of_the_wild@1.15.2-1.2.0 CREATE_REGISTRIES}
> 		GeneticAnimals-0_5_4.jar Genetic Animals {eanimod@0_5_4 CREATE_REGISTRIES}
> 		fairylights-3.0.8-1.15.2.jar Fairy Lights {fairylights@3.0.8 CREATE_REGISTRIES}
> 		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 CREATE_REGISTRIES}
> 		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 CREATE_REGISTRIES}
> 		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 CREATE_REGISTRIES}
> 		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 CREATE_REGISTRIES}
> 		collective-1.15.2-1.39.jar Collective {collective@1.39 CREATE_REGISTRIES}
> 		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
> 		DoubleSlabs-1.15-2.10.1.jar Double Slabs {doubleslabs@2.10.1 CREATE_REGISTRIES}
> 		infinitemusic-1.1.0.jar Infinite Music {infinitemusic@1.1.0 CREATE_REGISTRIES}
> 		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
> 		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
> 		fortunate-2.8.1-MC-1.15.jar How Fortunate! {fortunate@2.8.1-MC-1.15 CREATE_REGISTRIES}
> 		ModernUI-1.15.2-1.5.9.56-universal.jar Modern UI {modernui@1.5.9.56 ERROR}
> 		aawitherskull_1.15-1.1.jar Always a Wither Skull {aawitherskull@1.1 CREATE_REGISTRIES}
> 		easyelytrato_1.15.2-1.5.jar Easy Elytra Takeoff {easyelytrato@1.5 CREATE_REGISTRIES}
> 		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 CREATE_REGISTRIES}
> 		Cavern-Miner_1.15.2-v3.0.6.jar Cavern: Miner {cavern@3.0.6 CREATE_REGISTRIES}
> 		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 CREATE_REGISTRIES}
> 		grindstonesharpertools_1.15-1.4.jar Grindstone Sharper Tools {grindstonesharpertools@1.4 CREATE_REGISTRIES}
> 		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 CREATE_REGISTRIES}
> 		healingcf_1.15-2.3.jar Healing Campfire {healingcf@2.3 CREATE_REGISTRIES}
> 		portablelightsources-1.15.2-1.0.2.jar Portable Light Sources {portablelightsources@1.15.2-1.0.2 CREATE_REGISTRIES}
> 	Launched Version: 1.15.2-forge-31.2.30
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce GTX 980M/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by Tictim** [comment] 2020-08-22 05:28
That shouldn't be happening. I tested with Forge 31.2.36 and it seems to loading Paraglider just fine. Try with higher version of Forge. If the issue is still there, let me know so I can investigate further.

**Comment by Sweed-Le-Deedly** [comment] 2020-08-22 23:34
Tried getting a higher verson of Forge just now and found that it still
crashes to launcher and gives the same error.

Removed Paragliders from my mods folder and found that it still crashes to
launcher regardless, so I'm pretty certain one of my other mods has to be
outdated.

**Comment by Tictim** [comment] 2020-08-23 08:25
Then it's outside of my area, and I can't tell which mod is causing the error. Sorry.
I will close the issue since the issue doesn't seem to coming from Paragliders. If you found otherwise, please let me know.

**Closed as completed by Tictim** 2020-08-23 08:25 UTC

**Comment by Sweed-Le-Deedly** [comment] 2020-08-23 14:27
Found the problem; seems that Modern UI and Paragliders are incompatible
with each other.
