### ISSUE TITLE
Heart containers not updating Minecraft attribute. 

### ISSUE THREAD

**Issue by sappireflames000** [Tictim/Paraglider#105] opened 2023-12-03 04:08 UTC
So I am using the dawncraft modpack, and I have it set up to where every time I die in game, I lose one of my hearts. It worked for awhile, however I noticed that every time I gained a heart from a heart container my lowest allowed amount of hearts also increases. This is because the mod used to remove a heart every time I die uses minecrafts max_health generic attribute to tell how many hearts I have. Heart containers do not update this attribute, making so Minecraft thinks I still have 10 hearts when in reality I have 13. This has caused a lot of bugs to occur, and isn't ideal for what I am trying to do. I don't know how to reset my hearts to normal either, removing the mod doesn't help, my avatar is forever glitched unless I wipe the player data. Please fix :)

**Comment by Tictim** [comment] 2023-12-03 04:49
Just saying that we also make use of the max health attribute, as written [here](https://github.com/Tictim/Paraglider/blob/release/1.20.1/common/src/main/java/tictim/paraglider/impl/movement/ServerPlayerMovement.java#L85).

It is most likely that the issue is stemming from the other mod in question. I do not know what mod you are using, I am not aware of the "dawncraft" thing you mentioned, I don't even know what version of the mod you are using; but at least I remember the time when someone brought me an MCreator mod that caused max HP values to glitch out when combined with Heart Containers, and it turned out to be a naive implementation from that mod, thanks to MCreator's splendid approach on "simplification", if I had to guess.

I'll close this issue, as it is highly likely that this issue is caused by external factors. Let me know if you have something to add.

**Closed as completed by Tictim** 2023-12-03 04:49 UTC
