### ISSUE TITLE
[Suggestions] Feathers Api for stamina systems？

### ISSUE THREAD

**Issue by LFMaozi** [Tictim/Paraglider#80] opened 2023-06-07 09:36 UTC
[Feathers] https://www.curseforge.com/minecraft/mc-mods/feathers
"Feathers adds a set of blue feathers above the hunger bar [to be used by other mods](https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2) as a stamina system. The amount of feathers the player has access to is entirely dependent on the weight of their armor. Armor weight is automatically calculated but can be overwritten in the Config! The mod also contains a series of potion effects that directly affect the feathers mechanic, as well as a super simple to use API for modders to add their own support!"

**Comment by Tictim** [comment] 2023-08-17 06:24
Duplicate of #66.

Although native support for other stamina API isn't planned, an extension to the stamina system that enables other addons to implement custom stamina system for Paragliders, is currently work in progress.

**Closed as completed by Tictim** 2023-08-17 06:24 UTC
