### ISSUE TITLE
Health bug

### ISSUE THREAD

**Issue by megagnarxd** [Tictim/Paraglider#43] opened 2021-11-26 19:06 UTC
Using stats keeper, after you die, you will not respawn with hearts over 20.

https://www.curseforge.com/minecraft/mc-mods/stats-keeper

https://github.com/Terrails/StatsKeeper/issues/36

**Comment by megagnarxd** [comment] 2021-11-29 12:37
Ah, i guess it isn't fixed in 1.16? :( Was playing that version

**Comment by Tictim** [comment] 2021-11-30 06:35
The fix was only made in 1.17 because the issue got reproduced only in that version, and because it occurred regardless of other mod's presence. I cannot reproduce the same behavior in 1.16 either with or without the other mod.

Please search for other mods you installed.

Closing the issue for now. If you have something else to do with Paraglider, leave a comment.

**Comment by megagnarxd** [comment] 2021-11-30 12:25
https://youtu.be/SgkHjtRaAmo

please take a look

**Comment by Tictim** [comment] 2021-11-30 13:37
OK, so the issue wasn't about the vessels vanishing. I just discovered another irrelevant issue seeming to match the description of initial issue.

While it's all cool and good, I'd like to suggest making issues more descriptive next time - and provide the version.

Also you could have figured it out that Stats Keeper is nothing to do with the bug, if you ran the test without the mod installed 😛

**Closed as completed** 2021-11-30 13:50 UTC

**Comment by megagnarxd** [comment] 2021-11-30 14:08
I didn't know it as i was testing a modpack. But thanks for the fix, appreciate it :D will be more descriptive in the future
