### ISSUE TITLE
1.20.1 : goddess statue interface not opening

### ISSUE THREAD

**Issue by Daltaxy** [Tictim/Paraglider#94] opened 2023-10-13 15:34 UTC
Hello.
I hadn't played my world for quite some time; I come back and update everything, including forge to 47.2.1
Now, two things are broken. Going to any goddess statue and right clicking does nothing, no interface opens, and nothing seems to mention it in the log, that I'll include just in case
https://mclo.gs/XleKFNO
or 
[debug.log](https://github.com/Tictim/Paraglider/files/12895166/debug.log)
To be clear, I'm talking about the interface allowing you to give spirit orbs for paraglider stamina or hearts.
![ezgif-5-5a0e362a92](https://github.com/Tictim/Paraglider/assets/111076631/8f7cea3b-c798-4fd1-a94e-97a0f129ab8e)

update: doesn't work on a freshly created world either

**Comment by Tictim** [comment] 2023-12-03 05:41
The Goddess Statue, and Horned Statue, does not open GUI if no bargains are present. I don't know why there isn't any bargains, but considering the following excerpt from the log,
```
[13Oct2023 17:16:55.815] [Server thread/ERROR] [Paraglider/]: Found 6 issues in bargain recipes:
  Cannot resolve bargain type paraglider:goddess_statue for bargain recipes paraglider:goddess_statue/heart_container, paraglider:goddess_statue/stamina_vessel
  Cannot resolve bargain type paraglider:horned_statue for bargain recipes paraglider:horned_statue/sell_heart_container, paraglider:horned_statue/buy_stamina_vessel, paraglider:horned_statue/sell_stamina_vessel, paraglider:horned_statue/buy_heart_container
```
It is most likely that bargain type loading failed and recipe didn't get loaded as a result. I'm not sure if it's forge issue or mod incompatibility; try changing forge version, or swapping out mods for debug. Please let me know if you find anything.

**Comment by Daltaxy** [comment] 2023-12-03 10:43
> It is most likely that bargain type loading failed and recipe didn't get loaded as a result. I'm not sure if it's forge issue or mod incompatibility; try changing forge version, or swapping out mods for debug. Please let me know if you find anything.

Hello, I think that the mod in cause was Cyanide. 
I could be wrong, but it is similar to this issue 
#https://github.com/CyclopsMC/EverlastingAbilities/issues/239
where all the abilities were deleted due to the Cyanide mod.
Sadly I cannot test this right now as my whole curseforge is broken and does not recognise dependencies (libraries) when starting minecraft.
But I do think that the mod in cause was Cyanide, as qll this mess started after the owner of Terralith told me to get that mod. It also caused many crashes lol

**Comment by Tictim** [comment] 2023-12-04 06:26
Sounds plausible, since the bargain types are also defined as datapack entries.

I will close this issue for now, since it is likely to be caused by external factor; let me know if you have something else.

**Closed as completed by Tictim** 2023-12-04 06:26 UTC
